### PR TITLE
Basic CI integration (build and test)

### PR DESCRIPTION
**Pull request by cmb69**
See https://github.com/cmb69/pecl-php-uploadprogress/actions/runs/1090875298.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Awesome!

**Comment by williamdes** [comment]
You could probably disable fast finish
It would probably be nice to allow experimental version like you can see on the test workflow at phpMyAdmin/phpmyadmin for 8.1

**Comment by cmb69** [comment]
I think fail-fast generally makes sense; instead of disabling it, the failing tests should be fixed. :) Afterwards, the matrixes could easily be extended.

**Comment by williamdes** [comment]
> I think fail-fast generally makes sense; instead of disabling it, the failing tests should be fixed. :) Afterwards, the matrixes could easily be extended.

Yeah its true
What about adding 8.1 as experimental on the matrix?

**Comment by cmb69** [comment]
> What about adding 8.1 as experimental on the matrix?

That makes it more likely that 7.4 won't run – the only one that has a chance to succeed currently.

Also, I'm not sure whether any PR will be merged at all. :(

**Comment by williamdes** [comment]
Hi @remicollet 
Do you have some grants to merge PRs ?

**Comment by ramsey** [comment]
I just saw this after pushing this commit: https://github.com/php/pecl-php-uploadprogress/commit/c3b7b86f783762f53a6bdc7f583e92eb6f4ff666

Oops! Sorry.

**Comment by cmb69** [comment]
I had forgotten about this either. :)

**Pull request closed without merging**
