### PR TITLE
Prepare 2.x release

### PR DESCRIPTION
**Pull request by andypost**
Follow-up to https://github.com/php/pecl-php-uploadprogress/pull/3#issuecomment-578530653

Here's commits
- removal of php5 remains
- removal of usage of PHP_API_VERSION < 20190128
- TBD tests lcean-up

### CODE REVIEW

**Comment by andypost** [comment]
btw it build with php 7.3 and passes all tests
```
uploadprogress

uploadprogress support => enabled
Version => 1.1.1

Directive => Local Value => Master Value
uploadprogress.file.filename_template => /tmp/upt_%s.txt => /tmp/upt_%s.txt
uploadprogress.file.contents_template => /tmp/upload_contents_%s => /tmp/upload_contents_%s
uploadprogress.get_contents => 0 => 0

Build complete.
Don't forget to run 'make test'.


=====================================================================
PHP         : /usr/bin/php7 
PHP_SAPI    : cli
PHP_VERSION : 7.3.14
ZEND_VERSION: 3.3.14
PHP_OS      : Linux - Linux andy-HP 5.3.0-29-generic #31-Ubuntu SMP Fri Jan 17 17:27:26 UTC 2020 x86_64
INI actual  : /mnt/testing/php7-pecl-uploadprogress/src/pecl-php-uploadprogress-uploadprogress-1.1.2/tmp-php.ini
More .INIs  :   
CWD         : /mnt/testing/php7-pecl-uploadprogress/src/pecl-php-uploadprogress-uploadprogress-1.1.2
Extra dirs  : 
VALGRIND    : Not used
=====================================================================
TIME START 2020-01-27 00:58:00
=====================================================================
PASS uploadprogress_get_info - Filename containing spaces (bug #58318) [tests/bug58318.phpt] 
PASS uploadprogress_get_contents - Returns contents of uploading file [tests/uploadprogress_get_contents_basic.phpt] 
PASS uploadprogress_get_contents - Warns when function is disabled [tests/uploadprogress_get_contents_error001.phpt] 
PASS uploadprogress_get_contents - Warns when too few arguments [tests/uploadprogress_get_contents_error002.phpt] 
PASS uploadprogress_get_contents - Warns when maxlength is less than zero [tests/uploadprogress_get_contents_error003.phpt] 
SKIP uploadprogress_get_contents - Warns when too few arguments [tests/uploadprogress_get_contents_error004.phpt] reason: test only valid on PHP 8+
PASS uploadprogress_get_contents - When contents template is empty [tests/uploadprogress_get_contents_variation001.phpt] 
PASS uploadprogress_get_contents - File contents not found [tests/uploadprogress_get_contents_variation002.phpt] 
PASS uploadprogress_get_contents - Returns contents of file up to maxlen [tests/uploadprogress_get_contents_variation003.phpt] 
PASS uploadprogress_get_contents - Returns empty string for empty file [tests/uploadprogress_get_contents_variation004.phpt] 
PASS uploadprogress_get_contents - Template without replacement assumes directory [tests/uploadprogress_get_contents_variation005.phpt] 
PASS uploadprogress_get_contents - When contents file cannot be read [tests/uploadprogress_get_contents_variation006.phpt] 
PASS uploadprogress_get_info - Returns info for uploading file [tests/uploadprogress_get_info_basic.phpt] 
PASS uploadprogress_get_info - Warns when too few arguments [tests/uploadprogress_get_info_error001.phpt] 
PASS uploadprogress_get_info - File info not found [tests/uploadprogress_get_info_error002.phpt] 
PASS uploadprogress_get_info - When filename template is empty [tests/uploadprogress_get_info_error003.phpt] 
SKIP uploadprogress_get_info - Warns when too few arguments [tests/uploadprogress_get_info_error004.phpt] reason: test only valid on PHP 8+
PASS uploadprogress_get_info - Template without replacement assumes directory [tests/uploadprogress_get_info_variation001.phpt] 
PASS uploadprogress_get_info - When empty template and identifier [tests/uploadprogress_get_info_variation002.phpt] 
PASS uploadprogress_get_info - When info file cannot be read [tests/uploadprogress_get_info_variation003.phpt] 
PASS uploadprogress_get_info - Trims whitespace around keys and values [tests/uploadprogress_get_info_variation004.phpt] 
=====================================================================
TIME END 2020-01-27 00:58:00

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   12
---------------------------------------------------------------------

Number of tests :   21                19
Tests skipped   :    2 (  9.5%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   19 ( 90.5%) (100.0%)
---------------------------------------------------------------------
Time taken      :    0 seconds
```

**Comment by ramsey** [comment]
How do you feel about pointing this to the `2.x` branch instead?

**Comment by andypost** [comment]
Guts tells it should be major release, otoh api the same, not sure about how to handle it

**Comment by ramsey** [comment]
I'm planning to make a few (minor) changes to the API, and I think it would be good to hold this for a little while, and let the dust settle on 1.1.2. 😄

**Comment by ramsey** [comment]
This repo is now hooked up to Travis CI. (Thanks, @derickr!)

Please change the base branch for this PR to the `2.x` branch, and update the `.travis.yml` file to remove the older versions of PHP.

Thanks!

**Comment by andypost** [comment]
btw looking on https://travis-ci.org/php/pecl-php-uploadprogress/builds/642908095 I think all php 7.0 versions works

**Comment by ramsey** [comment]
With that in mind, maybe the minimum PHP version should be set to 7.2, since 7.2 is in "security support" mode until the end of November.

**Comment by andypost** [comment]
I bet `package.xml`will need polishing before release anyway so I left just minimal change

@ramsey is it common practice to exclude tests from packaging to pecl?

**Comment by ramsey** [comment]
It looks like all the other PECL extensions include their tests in the package, so if you want to add them, feel free. Do that in the `master` branch, though, and I’ll merge it up into the `2.x` branch.

**Comment by andypost** [comment]
After merging tests this one probably will need rebase

**Comment by ramsey** [comment]
I've rebased 2.x, so you'll need to rebase this branch. :-)

**Comment by williamdes** [comment]
:ping_pong: Just a hello, any updates?

**Comment by andypost** [comment]
I think it needs testing for 8.x beta first

**Comment by andypost** [comment]
Rebased to current master

**Comment by ramsey** [comment]
Oops! `nightly` isn't set up to allow failures on Travis CI. I'll take care of that tomorrow, so this get this merged.

**Comment by andypost** [comment]
Fixed arginfo with exact types, locally getting `tests/uploadprogress_get_info_variation003.phpt` to fail somehow (8.0 beta 1)
```
$ less tests/uploadprogress_get_info_variation003.diff

001+ array (
001- NULL
002+   'upload_id' => 'file004',
003+   'fieldname' => 'uploadFile',
004+   'filename' => 'example.txt',
005+   'time_start' => '1579893044',
006+   'time_last' => '30',
007+   'speed_average' => '300',
008+   'speed_last' => '300',
009+   'bytes_uploaded' => '1592342',
010+   'bytes_total' => '3000000',
011+   'files_uploaded' => '1',
012+   'est_sec' => '45',
013+ )
````

**Comment by andypost** [comment]
@ramsey it's great that nightly does not allow fail, btw last commit could be merged to 1.x branch as fixes required arginfo

**Comment by andypost** [comment]
Looks 2.x needs rebase commits from master... before merging it, I did add the commit to the MR because it for 2.x branch

**Comment by andypost** [comment]
@ramsey hey, is there chance to get it merged before 8.0 release?

**Comment by ramsey** [comment]
I'll look into it this week. Thanks for the nudge. 😁

**Comment by andypost** [comment]
Looks travis also needs fix as it starting to use xdebug 3

**Comment by andypost** [comment]
It needs PHP 8.1 nightly testing too

**Comment by andypost** [comment]
@ramsey Looks there's no travis anymore...

**Comment by williamdes** [comment]
> @ramsey Looks there's no travis anymore...

I can help migrate to GitHub actions but only if I am sure to have feedback as I may not have time if the review is on another week than when I do the migration ;)

**Comment by ramsey** [comment]
I deleted the `2.x` branch accidentally (it was even with `master` in the main repository), which closed this PR. Sorry about that. I recreated it and have reopened this PR. You'll need to rebase it to get it up-to-date.

**Comment by ramsey** [comment]
BTW, I've switched to using GitHub Actions and have dropped Travis CI. When you rebase, you'll get the new CI configuration.

**Comment by andypost** [comment]
Going to rebase against fresh master

**Comment by andypost** [comment]
Missed that 2.x is the same as master now, so here's commits for 2.x release

**Comment by andypost** [comment]
Now looks ready

**Comment by ramsey** [comment]
I apologize for the lengthy delay, but version 2.0.0 is released!

**Comment by andypost** [comment]
Thank you a lot for both releases @ramsey

**Comment by ramsey** [comment]
Thank you all for your patience. 😳

**Pull request merged**
